apiVersion: apps/v1
kind: Deployment
metadata:
  name: se-deployment
  labels:
    app: softether
spec:
  replicas: 1
  selector:
    matchLabels:
      name: softether
  template:
    metadata:
      labels:
        name: softether
        # softetherでkubednsを利用するためのNetworkPolicyを割り当てる
        vpn-server: "true"
    spec:
      containers:
      - name: softether
        image: ghcr.io/honahuku/softether:4.38.9760.v4
        ports:
        - containerPort: 443
