apiVersion: apps/v1
kind: Deployment
metadata:
  name: se-deployment
  labels:
    app: softether
spec:
  replicas: 1
  selector:
    matchLabels:
      name: softether
  template:
    metadata:
      labels:
        name: softether
        # softetherでkubednsを利用するためのNetworkPolicyを割り当てる
        vpn-server: "true"
    spec:
      containers:
      - name: softether
        image: ghcr.io/honahuku/softether:4.38.9760.v5
        ports:
        - containerPort: 443
---
# ネットワーク検証用環境
apiVersion: apps/v1
kind: Deployment
metadata:
  name: se-test
  labels:
    app: se-test
spec:
  replicas: 1
  selector:
    matchLabels:
      name: se-test
  template:
    metadata:
      labels:
        name: se-test
        # softetherでkubednsを利用するためのNetworkPolicyを割り当てる
        vpn-server: "true"
    spec:
      containers:
      - name: se-test
        image: ubuntu:22.04
        command: ['bash', '-c', 'sleep infinity']
