apiVersion: v1
kind: Service
metadata:
  name: se-service
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: se-service
  ports:
    - port: 443
      targetPort: 80
      nodePort: 30000
