apiVersion: v1
kind: Service
metadata:
  name: se-service
  annotations:
    service.beta.kubernetes.io/vultr-loadbalancer-protocol: "tcp"
spec:
  type: LoadBalancer
  selector:
    name: softether
  ports:
    - name: http
      port: 80
      targetPort: 443
